### PR TITLE
Feature/middle backend

### PR DESCRIPTION
**Pull request by 73359**
providing getAllBondTrades Endpoint for frontend

### CODE REVIEW

**Review by 73359 — COMMENTED** [review]
looks good, dogs are removed and first endpoint works

**Review by ranahiten8 — APPROVED** [review]
looks good to me

**Comment by kirserhat** [comment]
Looks good to me too.

**Review by ranahiten8 — APPROVED** [review]
Looks good

**Review by kirserhat — APPROVED** [review]

**Pull request merged**
